# Generated by Django 4.2.1 on 2023-05-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=12)),
                ("ticker_name", models.CharField(max_length=100)),
                ("closed_price", models.FloatField()),
                ("pred_1", models.FloatField()),
                ("pred_2", models.FloatField()),
                ("pred_3", models.FloatField()),
                ("pred_4", models.FloatField()),
                ("pred_5", models.FloatField()),
                ("pred_6", models.FloatField()),
                ("diff_1", models.FloatField(default=None)),
                ("error_1", models.FloatField(default=None)),
                ("diff_2", models.FloatField(default=None)),
                ("error_2", models.FloatField(default=None)),
                ("diff_3", models.FloatField(default=None)),
                ("error_3", models.FloatField(default=None)),
                ("diff_4", models.FloatField(default=None)),
                ("error_4", models.FloatField(default=None)),
                ("diff_5", models.FloatField(default=None)),
                ("error_5", models.FloatField(default=None)),
                ("diff_6", models.FloatField(default=None)),
                ("error_6", models.FloatField(default=None)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
