# Generated by Django 4.2.1 on 2023-05-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocks",
            name="diff_1",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="diff_2",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="diff_3",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="diff_4",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="diff_5",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="diff_6",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="error_1",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="error_2",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="error_3",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="error_4",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="error_5",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="error_6",
            field=models.FloatField(default=None, null=True),
        ),
    ]
